"""add_attraction_wishlist_ticket_order_fields

Revision ID: 04e188fec6fc
Revises: 394f8a2b1c6d
Create Date: 2026-06-05 07:34:20.489861
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e188fec6fc'
down_revision: Union[str, None] = '394f8a2b1c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attraction_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attraction_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attraction_id', 'ticket_type', name='uq_attraction_ticket_type')
    )
    op.create_index(op.f('ix_attraction_tickets_attraction_id'), 'attraction_tickets', ['attraction_id'], unique=False)
    op.create_table('attraction_wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('attraction_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'attraction_id', name='uq_user_attraction_wishlist')
    )
    op.add_column('attractions', sa.Column('ticket_price', sa.Float(), nullable=True))
    op.add_column('attractions', sa.Column('ticket_currency', sa.String(length=3), nullable=True))
    op.add_column('orders', sa.Column('attraction_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('attraction_ticket_id', sa.UUID(), nullable=True))
    op.alter_column('orders', 'tour_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'attractions', ['attraction_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'attraction_tickets', ['attraction_ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'tour_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orders', 'attraction_ticket_id')
    op.drop_column('orders', 'attraction_id')
    op.drop_column('attractions', 'ticket_currency')
    op.drop_column('attractions', 'ticket_price')
    op.drop_table('attraction_wishlists')
    op.drop_index(op.f('ix_attraction_tickets_attraction_id'), table_name='attraction_tickets')
    op.drop_table('attraction_tickets')
    # ### end Alembic commands ###
